[package]
name = "lamdap"
version = "0.1.0"
entrypoint = "export.typ"
authors = ["pacaunt <@pacaunt>"]
license = "MIT"
compiler = "0.14.0"
repository = "https://github.com/pacaunt/listinum"
description = "Simple List and Enum Layout"
categories = ["utility"]
